"""Retest executer agent."""

from __future__ import annotations

from server.agents.executer.base import BaseExecuterAgent, ExecuterCallback, ExecuterResult
from server.config.agent import LocalLLMConfig, PublicLLMConfig

from .config import (
    LLM_CALL_TIMEOUT_SECONDS,
    MAX_TOOL_ROUNDS,
    RETEST_CONTEXT_WINDOW_MAX_TOKENS,
    RETEST_CONTEXT_WINDOW_SEND_THRESHOLD_TOKENS,
    RETEST_MAX_TOOL_CALLS_PER_ROUND,
)
from .context_window import RETEST_CONTEXT_WINDOW_KEY
from .policy import (
    build_retest_scenario_packet,
    format_retest_context_for_packet,
)
from .prompts import SYSTEM_PROMPT
from .tools import ALL_RETEST_TOOLS


class RetestExecuterAgent(BaseExecuterAgent):
    """
    Verifies remediation effectiveness through payload replay and bypass testing.

    Capabilities:
    - Payload replay with exact original attack parameters
    - LLM-generated bypass mutations to test patch robustness
    - ML-based patch_confidence scoring (0.0-1.0)
    - Regression detection across multiple test iterations
    - Differential analysis between original and retest responses

    Verdict options:
    - fixed: Vulnerability fully remediated
    - partial: Some bypass variants still work
    - not_fixed: Original payload still works
    - bypassed: Original blocked but mutations succeed
    - regression: Previously fixed vulnerability reappeared
    """

    def __init__(
        self,
        *,
        mode: str | None = None,
        callback: ExecuterCallback | None = None,
        config: PublicLLMConfig | None = None,
        local_config: LocalLLMConfig | None = None,
        project_id: str | None = None,
        project_cache_dir: str | None = None,
    ) -> None:
        super().__init__(
            role="retest",
            system_prompt=SYSTEM_PROMPT,
            tools=ALL_RETEST_TOOLS,
            max_tool_rounds=MAX_TOOL_ROUNDS,
            max_tool_calls_per_round=RETEST_MAX_TOOL_CALLS_PER_ROUND,
            call_timeout_seconds=LLM_CALL_TIMEOUT_SECONDS,
            mode=mode,
            callback=callback,
            config=config,
            local_config=local_config,
            project_id=project_id,
            project_cache_dir=project_cache_dir,
            context_window_key=RETEST_CONTEXT_WINDOW_KEY,
            context_window_max_tokens=RETEST_CONTEXT_WINDOW_MAX_TOKENS,
        )

    async def run(self, user_message: str) -> ExecuterResult:
        context_block = "Context window disabled (missing project_id)."
        if self._context_window is not None:
            await self._context_window.ensure_token_budget(
                threshold_tokens=RETEST_CONTEXT_WINDOW_SEND_THRESHOLD_TOKENS
            )
            snapshot = self._context_window.snapshot()
            context_block = format_retest_context_for_packet(snapshot)

        packet = build_retest_scenario_packet(
            scenario_and_target=user_message,
            context_block=context_block,
            available_tools=sorted(self._tools.keys()),
        )
        return await super().run(packet)
