"""Curated web recon security tool catalog for run_custom usage.

This catalog supplements the live web recon runtime. Smart Python tools remain
active until each wrapper has a real alias-backed or router-backed replacement.
"""

from __future__ import annotations

WEB_RECON_TOOLS: dict[str, dict[str, object]] = {

    # ── PHASE 1: PASSIVE OSINT ─────────────────────────────────────────────
    "subfinder": {
        "phase": 1,
        "type": "subdomain_enum",
        "when": ["find subdomains passively", "initial domain asset discovery", "feed subdomain list to other tools"],
        "targets": ["domain"],
        "cmd": "subfinder -d TARGET -all -silent",
        "pipe_into": ["dnsx", "httpx", "nuclei"],
    },
    "amass": {
        "phase": 1,
        "type": "subdomain_enum",
        "when": ["deep passive+active subdomain enum", "ASN and CIDR mapping", "relationship graph across assets", "when subfinder misses subdomains"],
        "targets": ["domain", "org"],
        "cmd": "amass enum -passive -d TARGET -config ~/.config/amass/config.ini",
        "pipe_into": ["dnsx", "httpx"],
    },
    "assetfinder": {
        "phase": 1,
        "type": "subdomain_enum",
        "when": ["fast lightweight passive subdomain sweep", "quick pipeline input"],
        "targets": ["domain"],
        "cmd": "assetfinder --subs-only TARGET",
        "pipe_into": ["dnsx", "httpx"],
    },
    "theHarvester": {
        "phase": 1,
        "type": "osint_harvest",
        "when": ["harvest emails and employee names", "find IPs and hostnames from search engines", "OSINT before active scanning"],
        "targets": ["domain", "org"],
        "cmd": "theHarvester -d TARGET -b all",
        "pipe_into": [],
    },
    "shodan": {
        "phase": 1,
        "type": "internet_search",
        "when": ["find exposed services without touching target", "banner grabbing at scale", "locate IPs running specific products or CVEs"],
        "targets": ["ip", "org", "product"],
        "cmd": "shodan search 'hostname:TARGET' --fields ip_str,port,org,os",
        "pipe_into": ["nmap", "nuclei"],
    },
    "censys": {
        "phase": 1,
        "type": "internet_search",
        "when": ["SSL cert and TLS config analysis", "discover assets via certificate transparency", "alternative to shodan for cert-heavy recon"],
        "targets": ["domain", "ip", "cert"],
        "cmd": "censys search 'parsed.names: TARGET' --index-type certificates",
        "pipe_into": ["nmap"],
    },
    "crt_sh": {
        "phase": 1,
        "type": "cert_transparency",
        "when": ["enumerate subdomains from SSL certificates", "zero-noise passive recon", "no API key needed"],
        "targets": ["domain"],
        "cmd": "curl -s 'https://crt.sh/?q=%25.TARGET&output=json' | jq -r '.[].name_value' | sort -u",
        "pipe_into": ["dnsx", "httpx"],
    },
    "gau": {
        "phase": 1,
        "type": "url_harvest",
        "when": ["mine historical URLs from Wayback and Common Crawl", "find old endpoints and parameters", "discover forgotten paths"],
        "targets": ["domain"],
        "cmd": "gau TARGET --threads 5",
        "pipe_into": ["ffuf", "nuclei"],
    },
    "waybackurls": {
        "phase": 1,
        "type": "url_harvest",
        "when": ["pull URLs from Wayback Machine specifically", "simpler alternative to gau for archive mining"],
        "targets": ["domain"],
        "cmd": "echo TARGET | waybackurls",
        "pipe_into": ["ffuf"],
    },
    "paramspider": {
        "phase": 1,
        "type": "param_harvest",
        "when": ["extract parameters from archived URLs", "seed parameter lists for fuzzing and injection testing"],
        "targets": ["domain"],
        "cmd": "paramspider -d TARGET",
        "pipe_into": ["ffuf", "dalfox"],
    },
    "trufflehog": {
        "phase": 1,
        "type": "secret_scan",
        "when": ["scan git repos for leaked API keys and secrets", "find hardcoded credentials in source code", "check public repos of target org"],
        "targets": ["github_repo", "git_url"],
        "cmd": "trufflehog git https://github.com/ORG/REPO --only-verified",
        "pipe_into": [],
    },
    "github_dork": {
        "phase": 1,
        "type": "osint_harvest",
        "when": ["find secrets and internal references in public GitHub", "look for config files, tokens, internal URLs"],
        "targets": ["org", "domain"],
        "cmd": "# Search GitHub: org:TARGET password OR secret OR api_key OR internal",
        "pipe_into": [],
    },
    "cloudbrute": {
        "phase": 1,
        "type": "cloud_enum",
        "when": ["discover exposed cloud storage buckets", "find open S3, GCS, Azure blobs for target org", "cloud asset enumeration before active scanning"],
        "targets": ["org", "keyword"],
        "cmd": "cloudbrute -d TARGET -k keyword -m storage",
        "pipe_into": [],
    },
    "s3scanner": {
        "phase": 1,
        "type": "cloud_enum",
        "when": ["scan for misconfigured S3 buckets specifically", "check bucket permissions and public read/write access"],
        "targets": ["bucket_name", "domain"],
        "cmd": "s3scanner scan --bucket TARGET",
        "pipe_into": [],
    },

    # ── PHASE 2: DNS & ASSET VALIDATION ───────────────────────────────────
    "dnsx": {
        "phase": 2,
        "type": "dns_resolve",
        "when": ["validate which subdomains resolve", "A/CNAME/MX/TXT record lookup at scale", "filter dead subdomains before active scanning"],
        "targets": ["subdomain_list"],
        "cmd": "dnsx -l subfinder.txt -a -resp -silent",
        "pipe_into": ["httpx", "nmap"],
    },
    "massdns": {
        "phase": 2,
        "type": "dns_bruteforce",
        "when": ["high-speed DNS brute forcing", "resolve massive wordlists fast", "when dnsx is too slow for large lists"],
        "targets": ["domain", "wordlist"],
        "cmd": "massdns -r resolvers.txt -t A -o S wordlist.txt",
        "pipe_into": ["httpx"],
    },
    "alterx": {
        "phase": 2,
        "type": "subdomain_permutation",
        "when": ["generate subdomain permutations from known subs", "find staging/dev/internal variants"],
        "targets": ["subdomain_list"],
        "cmd": "alterx -l resolved.txt -silent | dnsx -silent",
        "pipe_into": ["httpx"],
    },
    "subjack": {
        "phase": 2,
        "type": "takeover_detection",
        "when": ["detect subdomain takeover vulnerabilities", "check dangling CNAME records pointing to unclaimed services"],
        "targets": ["subdomain_list"],
        "cmd": "subjack -w resolved.txt -t 100 -timeout 30 -ssl -v",
        "pipe_into": [],
    },

    # ── PHASE 3: HTTP PROBING & FINGERPRINTING ─────────────────────────────
    "httpx": {
        "phase": 3,
        "type": "http_probe",
        "when": ["check which hosts are live HTTP/S", "fingerprint tech stack, status codes, titles", "validate before deeper scanning"],
        "targets": ["subdomain_list", "ip_list"],
        "cmd": "httpx -l resolved.txt -silent -title -tech-detect -status-code -cl -ct",
        "pipe_into": ["nuclei", "katana", "ffuf"],
    },
    "whatweb": {
        "phase": 3,
        "type": "fingerprint",
        "when": ["detailed framework and CMS fingerprinting on single target", "when httpx tech-detect is insufficient"],
        "targets": ["url"],
        "cmd": "whatweb -a 3 TARGET",
        "pipe_into": ["wpscan", "cmseek"],
    },
    "wafw00f": {
        "phase": 3,
        "type": "waf_detect",
        "when": ["detect WAF before fuzzing to plan bypass", "identify filtering layer"],
        "targets": ["url"],
        "cmd": "wafw00f TARGET",
        "pipe_into": [],
    },
    "masscan": {
        "phase": 3,
        "type": "port_scan",
        "when": ["ultra-fast port scan across large IP ranges", "initial open port sweep before nmap deep scan", "when nmap is too slow for wide scope"],
        "targets": ["ip_range", "cidr"],
        "cmd": "masscan TARGET -p0-65535 --rate 10000",
        "pipe_into": ["nmap"],
    },
    "nmap": {
        "phase": 3,
        "type": "port_scan",
        "when": ["discover open ports and running services", "service version detection", "run NSE scripts for vuln detection", "deep scan after masscan sweep"],
        "targets": ["ip", "host"],
        "cmd": "nmap -sV -sC -p- --open -T4 TARGET",
        "pipe_into": ["nuclei"],
    },

    # ── PHASE 4: CONTENT DISCOVERY ─────────────────────────────────────────
    "ffuf": {
        "phase": 4,
        "type": "fuzzer",
        "when": ["directory and file brute force", "parameter fuzzing", "vhost discovery", "fastest fuzz option"],
        "targets": ["url"],
        "cmd": "ffuf -u TARGET/FUZZ -w wordlists/web/folders.txt -mc 200,204,301,302,307,401,403",
        "pipe_into": [],
    },
    "feroxbuster": {
        "phase": 4,
        "type": "fuzzer",
        "when": ["recursive content discovery", "find nested hidden paths", "when ffuf misses deep structure"],
        "targets": ["url"],
        "cmd": "feroxbuster -u TARGET -w wordlists/web/folders.txt --silent",
        "pipe_into": [],
    },
    "gobuster": {
        "phase": 4,
        "type": "fuzzer",
        "when": ["extension-aware path discovery", "DNS subdomain brute force mode", "simple fast alternative to ffuf"],
        "targets": ["url", "domain"],
        "cmd": "gobuster dir -u TARGET -w wordlists/web/folders.txt -x php,js,json,bak",
        "pipe_into": [],
    },
    "katana": {
        "phase": 4,
        "type": "crawler",
        "when": ["crawl live web app for routes and endpoints", "parse JS for client-side paths and APIs", "map SPA surfaces"],
        "targets": ["url"],
        "cmd": "katana -u TARGET -jc -js -d 5 -silent",
        "pipe_into": ["ffuf", "nuclei"],
    },
    "linkfinder": {
        "phase": 4,
        "type": "js_endpoint_extract",
        "when": ["extract endpoints and paths from JS files at runtime", "find hidden API routes embedded in JS", "deeper than subjs which only harvests JS URLs"],
        "targets": ["js_url", "url"],
        "cmd": "python3 linkfinder.py -i TARGET -o cli",
        "pipe_into": ["ffuf", "nuclei"],
    },

    # ── PHASE 5: VULNERABILITY SCANNING ───────────────────────────────────
    "nuclei": {
        "phase": 5,
        "type": "vuln_scanner",
        "when": ["template-driven vuln detection across all live hosts", "check misconfigs, exposed panels, CVEs", "automate known-exposure checks"],
        "targets": ["url_list", "url"],
        "cmd": "nuclei -u TARGET -severity critical,high,medium",
        "pipe_into": [],
    },
    "nikto": {
        "phase": 5,
        "type": "vuln_scanner",
        "when": ["classic web server misconfiguration scan", "quick check for outdated software and default files"],
        "targets": ["url"],
        "cmd": "nikto -h TARGET",
        "pipe_into": [],
    },
    "corsy": {
        "phase": 5,
        "type": "cors_scan",
        "when": ["detect CORS misconfiguration", "find overly permissive Access-Control-Allow-Origin headers", "check for origin reflection and wildcard abuse"],
        "targets": ["url"],
        "cmd": "python3 corsy.py -u TARGET -t 10",
        "pipe_into": [],
    },

    # ── PHASE 6: SPECIALIZED RECON ─────────────────────────────────────────
    "curl": {
        "phase": 6,
        "type": "http_manual",
        "when": ["manual header inspection", "validate specific endpoints", "cookie and auth flow probing"],
        "targets": ["url"],
        "cmd": "curl -i -sS -A 'Mozilla/5.0' TARGET",
        "pipe_into": [],
    },
    "wpscan": {
        "phase": 6,
        "type": "cms_scan",
        "when": ["target is WordPress", "enumerate plugins, themes, users, and known CVEs"],
        "targets": ["wordpress_url"],
        "cmd": "wpscan --url TARGET --no-update -e vp,vt,tt,cb,dbe,u,m --api-token TOKEN",
        "pipe_into": [],
    },
    "cmseek": {
        "phase": 6,
        "type": "cms_scan",
        "when": ["unknown CMS — detect and fingerprint first", "initial CMS family identification"],
        "targets": ["url"],
        "cmd": "cmseek --batch --random-agent -u TARGET",
        "pipe_into": ["wpscan", "joomscan", "droopescan"],
    },
    "joomscan": {
        "phase": 6,
        "type": "cms_scan",
        "when": ["target is Joomla", "enumerate components and known misconfigs"],
        "targets": ["joomla_url"],
        "cmd": "joomscan -u TARGET",
        "pipe_into": [],
    },
    "droopescan": {
        "phase": 6,
        "type": "cms_scan",
        "when": ["target is Drupal", "module and version discovery"],
        "targets": ["drupal_url"],
        "cmd": "droopescan scan drupal -u TARGET",
        "pipe_into": [],
    },
    "retire_js": {
        "phase": 6,
        "type": "js_analysis",
        "when": ["detect vulnerable client-side JS libraries", "CVE mapping on frontend dependencies"],
        "targets": ["url", "js_path"],
        "cmd": "retire --js --path TARGET",
        "pipe_into": [],
    },
    "subjs": {
        "phase": 6,
        "type": "js_analysis",
        "when": ["harvest all JS file URLs from a target", "feed JS files to secret scanners or retire.js"],
        "targets": ["url"],
        "cmd": "subjs -u TARGET",
        "pipe_into": ["retire_js", "trufflehog", "linkfinder"],
    },
    "gowitness": {
        "phase": 6,
        "type": "screenshot",
        "when": ["visually inspect and triage large lists of live hosts", "prioritize targets by rendered content", "actively maintained alternative to aquatone"],
        "targets": ["url_list"],
        "cmd": "gowitness scan file -f live_urls.txt --threads 10",
        "pipe_into": [],
    },
    "jwt_tool": {
        "phase": 6,
        "type": "auth_analysis",
        "when": ["inspect and abuse JWT tokens", "test alg confusion, none attack, weak secrets"],
        "targets": ["jwt_token"],
        "cmd": "jwt_tool TOKEN -C -d wordlists/jwt_secrets.txt",
        "pipe_into": [],
    },
    "inql": {
        "phase": 6,
        "type": "graphql_recon",
        "when": ["target exposes a GraphQL endpoint", "introspect schema, map queries and mutations"],
        "targets": ["graphql_url"],
        "cmd": "inql -t TARGET/graphql",
        "pipe_into": [],
    },
    "grpcurl": {
        "phase": 6,
        "type": "grpc_recon",
        "when": ["target uses gRPC", "enumerate services and methods via reflection"],
        "targets": ["grpc_host"],
        "cmd": "grpcurl -plaintext TARGET:50051 list",
        "pipe_into": [],
    },
    "mitmproxy": {
        "phase": 6,
        "type": "proxy",
        "when": ["intercept and modify traffic programmatically", "capture WebSocket or gRPC/HTTP2 flows", "replay and tamper requests with scripts"],
        "targets": ["http_traffic", "websocket", "mobile_backend"],
        "cmd": "mitmproxy -p 8080",
        "pipe_into": [],
    },
}

web_recon_tools = WEB_RECON_TOOLS
