"""Report generation, retrieval, and protected export routes."""

from __future__ import annotations

import asyncio
import io
import os
import re
import shutil
import subprocess
import tempfile
import uuid
from pathlib import Path

import markdown as md
import structlog
from bs4 import BeautifulSoup
from fastapi import APIRouter, HTTPException, Response
from pypdf import PdfReader, PdfWriter
from pydantic import BaseModel, Field

try:
    from xhtml2pdf import pisa
except Exception:  # pragma: no cover - optional dependency fallback
    pisa = None

from server.agents.report.report_generator import generate_report
from server.api.dependencies import projects_store

router = APIRouter(tags=["reports"])
logger = structlog.get_logger(__name__)
_report_tasks: dict[str, asyncio.Task[None]] = {}


class GenerateReportResponse(BaseModel):
    ok: bool = True
    run_id: str = ""
    status: str = "pending"
    report_id: str = ""
    format: str = "markdown"
    created_at: str = ""


class ReportStatusResponse(BaseModel):
    markdown: bool = False
    html: bool = False
    pdf: bool = False
    generated_at: str | None = None
    run_id: str | None = None
    run_status: str | None = None


class ReportContentResponse(BaseModel):
    ok: bool = True
    format: str = "markdown"
    content: str = ""
    metadata: dict = {}
    created_at: str = ""


class UpdateReportRequest(BaseModel):
    content: str


class ExportReportRequest(BaseModel):
    format: str = Field(default="markdown")
    password: str = Field(min_length=1, max_length=256)


_HTML_REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PentaForge Pentest Report — {target}</title>
<style>
  :root {{
    --bg: #ffffff;
    --surface: #f8fafc;
    --border: #e2e8f0;
    --text: #1e293b;
    --text-muted: #64748b;
    --accent: #4f46e5;
    --critical: #ef4444;
    --high: #f97316;
    --medium: #eab308;
    --low: #3b82f6;
    --info: #6b7280;
    --heading: #0f172a;
  }}
  [data-theme="dark"] {{
    --bg: #0c1220;
    --surface: #111827;
    --border: #1e293b;
    --text: #e2e8f0;
    --text-muted: #94a3b8;
    --accent: #6366f1;
    --heading: #f1f5f9;
  }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    color-scheme: light dark;
    line-height: 1.7;
    padding: 2rem;
    max-width: 960px;
    margin: 0 auto;
  }}
  h1 {{ font-size:1.8rem; margin:1.5rem 0 1rem; color:var(--heading); border-bottom:2px solid var(--accent); padding-bottom:.5rem; }}
  h2 {{ font-size:1.4rem; margin:1.5rem 0 .8rem; color:var(--heading); }}
  h3 {{ font-size:1.1rem; margin:1.2rem 0 .5rem; color:var(--heading); }}
  p {{ margin:.5rem 0; }}
  ul, ol {{ margin:.5rem 0 .5rem 1.5rem; }}
  li {{ margin:.25rem 0; }}
  code {{
    background: var(--surface);
    padding: .15em .4em;
    border-radius: 4px;
    font-size: .9em;
    border: 1px solid var(--border);
  }}
  pre {{
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    border: 1px solid var(--border);
    overflow-x: auto;
    margin: .5rem 0;
    font-size: .85em;
  }}
  pre code {{ background:none; border:none; padding:0; }}
  table {{
    width:100%;
    border-collapse:collapse;
    margin:.5rem 0;
  }}
  th, td {{
    padding:.5rem .75rem;
    border:1px solid var(--border);
    text-align:left;
  }}
  th {{ background:var(--surface); font-weight:600; color:var(--heading); }}
  strong {{ color:var(--heading); }}
  a {{ color: var(--accent); text-decoration:none; }}
  a:hover {{ text-decoration:underline; }}
  hr {{ border:none; border-top:1px solid var(--border); margin:1.5rem 0; }}
  .header {{
    text-align:center;
    padding:2rem 0;
    border-bottom:2px solid var(--accent);
    margin-bottom:2rem;
  }}
  .header h1 {{ border:none; font-size:2rem; }}
  .header p {{ color:var(--text-muted); font-size:.9rem; }}
  .footer {{
    text-align:center;
    padding:2rem 0;
    border-top:1px solid var(--border);
    margin-top:2rem;
    color:var(--text-muted);
    font-size:.8rem;
  }}
  @media print {{
    body {{ background:#fff; color:#1a1a1a; }}
    h1, h2, h3, strong {{ color:#0f172a; }}
    code {{ background:#f1f5f9; border-color:#e2e8f0; }}
    pre {{ background:#f8fafc; border-color:#e2e8f0; }}
    .header {{ border-color:#6366f1; }}
  }}
</style>
</head>
<body>
<div class="header">
  <h1>PentaForge Penetration Test Report</h1>
  <p>Target: {target} &mdash; Generated: {generated_at}</p>
</div>
{body}
<div class="footer">
  <p>Generated by PentaForge &mdash; Automated Penetration Testing Platform</p>
</div>
</body>
</html>
"""

_PDF_EXPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
  body {{
    font-family: Helvetica, Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #1f2937;
    margin: 28pt 34pt;
  }}
  h1 {{
    font-size: 20pt;
    margin: 0 0 10pt;
    color: #111827;
    border-bottom: 2pt solid #dc2626;
    padding-bottom: 6pt;
  }}
  h2 {{
    font-size: 15pt;
    margin: 18pt 0 8pt;
    color: #111827;
  }}
  h3 {{
    font-size: 12pt;
    margin: 12pt 0 6pt;
    color: #111827;
  }}
  p {{
    margin: 0 0 8pt;
  }}
  ul, ol {{
    margin: 0 0 10pt 18pt;
  }}
  li {{
    margin: 0 0 4pt;
  }}
  code, pre {{
    font-family: Courier, monospace;
    font-size: 9pt;
  }}
  pre {{
    white-space: pre-wrap;
    border: 1pt solid #d1d5db;
    background: #f9fafb;
    padding: 8pt;
    margin: 8pt 0;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 10pt 0;
  }}
  th, td {{
    border: 1pt solid #d1d5db;
    padding: 6pt;
    text-align: left;
    vertical-align: top;
  }}
  th {{
    background: #f3f4f6;
  }}
  .meta {{
    color: #6b7280;
    font-size: 9pt;
    margin-bottom: 18pt;
  }}
</style>
</head>
<body>
  <h1>{title}</h1>
  <p class="meta">Generated by PentaForge for project {project_id}</p>
  {body}
</body>
</html>
"""

_PDF_LINE_RE = re.compile(r"\s+")
_PDF_PAGE_WIDTH = 612
_PDF_PAGE_HEIGHT = 792
_PDF_LEFT_MARGIN = 50
_PDF_TOP_Y = 742
_PDF_LEADING = 14
_PDF_FONT_SIZE = 10
_PDF_LINES_PER_PAGE = 46


def _markdown_to_html(markdown_content: str, target: str, generated_at: str) -> str:
    """Convert markdown report to styled HTML."""
    content = markdown_content.strip()
    # Remove LLM wrapping if present
    if content.startswith("```markdown"):
        content = content[len("```markdown") :].strip()
        if content.endswith("```"):
            content = content[:-3].strip()
    elif content.startswith("```"):
        content = content[3:].strip()
        if content.endswith("```"):
            content = content[:-3].strip()

    body = md.markdown(
        content,
        extensions=["tables", "fenced_code", "toc"],
    )
    return _HTML_REPORT_TEMPLATE.format(
        target=target,
        generated_at=generated_at,
        body=body,
    )


def _strip_markdown_fences(content: str) -> str:
    text = str(content or "").strip()
    if text.startswith("```markdown"):
        text = text[len("```markdown") :].strip()
        if text.endswith("```"):
            text = text[:-3].strip()
    elif text.startswith("```"):
        text = text[3:].strip()
        if text.endswith("```"):
            text = text[:-3].strip()
    return text


def _normalize_pdf_line(value: str) -> str:
    safe = _PDF_LINE_RE.sub(" ", str(value or "").strip())
    if not safe:
        return ""
    return safe.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _plain_text_from_report(format_name: str, content: str) -> str:
    safe_format = str(format_name or "").strip().lower()
    raw = str(content or "")
    if safe_format == "html":
        text = BeautifulSoup(raw, "html.parser").get_text("\n")
    else:
        text = _strip_markdown_fences(raw)
    lines = [line.rstrip() for line in text.splitlines()]
    return "\n".join(lines).strip()


def _build_plain_pdf_bytes(title: str, text: str) -> bytes:
    import textwrap

    normalized_title = _normalize_pdf_line(title or "PentaForge Report")
    source_lines = [line.rstrip() for line in str(text or "").splitlines()]
    wrapped_lines: list[str] = []
    for line in source_lines:
        clean = line.strip()
        if not clean:
            wrapped_lines.append("")
            continue
        for chunk in textwrap.wrap(clean, width=95, replace_whitespace=False, drop_whitespace=False):
            wrapped_lines.append(chunk.rstrip())
    if not wrapped_lines:
        wrapped_lines = ["PentaForge report export"]

    pages: list[list[str]] = []
    for index in range(0, len(wrapped_lines), _PDF_LINES_PER_PAGE):
        pages.append(wrapped_lines[index : index + _PDF_LINES_PER_PAGE])

    objects: list[bytes] = []
    page_ids: list[int] = []
    content_ids: list[int] = []
    font_obj_id = 3

    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Kids [] /Count 0 >>")
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>")

    next_obj_id = 4
    for lines in pages:
        content_lines = [
            "BT",
            f"/F1 {_PDF_FONT_SIZE} Tf",
            f"{_PDF_LEFT_MARGIN} {_PDF_TOP_Y} Td",
            f"{_PDF_LEADING} TL",
        ]
        if normalized_title:
            content_lines.append(f"({normalized_title}) Tj")
            content_lines.append("T*")
            content_lines.append("T*")
        for line in lines:
            escaped = _normalize_pdf_line(line)
            if escaped:
                content_lines.append(f"({escaped}) Tj")
            content_lines.append("T*")
        content_lines.append("ET")
        stream = "\n".join(content_lines).encode("latin-1", errors="replace")
        content_obj_id = next_obj_id
        page_obj_id = next_obj_id + 1
        next_obj_id += 2
        content_ids.append(content_obj_id)
        page_ids.append(page_obj_id)
        objects.append(
            b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream"
        )
        objects.append(
            (
                f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {_PDF_PAGE_WIDTH} {_PDF_PAGE_HEIGHT}] "
                f"/Resources << /Font << /F1 {font_obj_id} 0 R >> >> /Contents {content_obj_id} 0 R >>"
            ).encode("ascii")
        )

    kids = " ".join(f"{page_id} 0 R" for page_id in page_ids) or ""
    objects[1] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_ids)} >>".encode("ascii")

    pdf = io.BytesIO()
    pdf.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for obj_id, obj in enumerate(objects, start=1):
        offsets.append(pdf.tell())
        pdf.write(f"{obj_id} 0 obj\n".encode("ascii"))
        pdf.write(obj)
        pdf.write(b"\nendobj\n")

    xref_offset = pdf.tell()
    pdf.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.write(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf.write(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF\n"
        ).encode("ascii")
    )
    return pdf.getvalue()


def _encrypt_pdf_bytes(pdf_bytes: bytes, password: str) -> bytes:
    reader = PdfReader(io.BytesIO(pdf_bytes))
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    writer.encrypt(password, algorithm="AES-256-R5")
    output = io.BytesIO()
    writer.write(output)
    return output.getvalue()


def _build_html_pdf_bytes(html_content: str) -> bytes | None:
    if pisa is None:
        return None

    source = str(html_content or "").strip()
    if not source:
        return None

    output = io.BytesIO()
    result = pisa.CreatePDF(source, dest=output)
    if result.err:
        return None
    return output.getvalue()


def _html_for_pdf_export(*, project_id: str, content: str, source_format: str) -> str:
    safe_format = str(source_format or "").strip().lower()
    if safe_format == "html":
        soup = BeautifulSoup(str(content or ""), "html.parser")
        for tag in soup(["script", "style"]):
            tag.decompose()
        body = soup.body
        body_html = "".join(str(child) for child in body.contents) if body else str(content or "")
    else:
        body_html = md.markdown(
            _strip_markdown_fences(content),
            extensions=["tables", "fenced_code"],
        )
    return _PDF_EXPORT_TEMPLATE.format(
        title="PentaForge Penetration Test Report",
        project_id=project_id,
        body=body_html,
    )


def _build_pdf_export_bytes(*, project_id: str, content: str, source_format: str) -> bytes:
    html_pdf = _build_html_pdf_bytes(
        _html_for_pdf_export(
            project_id=project_id,
            content=content,
            source_format=source_format,
        )
    )
    if html_pdf:
        return html_pdf

    title = f"PentaForge Report - {project_id}"
    text = _plain_text_from_report(source_format, content)
    return _build_plain_pdf_bytes(title, text)


def _build_protected_zip_bytes(
    *,
    inner_name: str,
    payload: bytes,
    password: str,
    encryption_method: str = "ZipCrypto",
) -> bytes:
    seven_zip = shutil.which("7z")
    if not seven_zip:
        raise RuntimeError("7z is required for protected report export but is not installed.")

    with tempfile.TemporaryDirectory(prefix="pf-report-export-") as temp_dir:
        temp_path = Path(temp_dir)
        inner_path = temp_path / inner_name
        archive_path = temp_path / f"{inner_name}.zip"
        inner_path.write_bytes(payload)
        result = subprocess.run(
            [
                seven_zip,
                "a",
                "-tzip",
                f"-mem={encryption_method}",
                f"-p{password}",
                "-y",
                str(archive_path),
                str(inner_path.name),
            ],
            cwd=temp_dir,
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0 or not archive_path.exists():
            stderr = (result.stderr or result.stdout or "").strip()
            raise RuntimeError(f"Failed to build protected archive: {stderr or '7z returned a non-zero exit code.'}")
        return archive_path.read_bytes()


def _persist_report_run(
    *,
    project_id: str,
    run_id: str,
    status: str,
    payload: dict,
) -> None:
    projects_store.upsert_task_run(
        run_id=run_id,
        project_id=project_id,
        task_type="report",
        status=status,
        payload=payload,
    )


async def _generate_project_report_task(project_id: str, run_id: str) -> None:
    payload: dict = {
        "project_id": project_id,
        "report_id": "",
        "format": "markdown",
        "error": "",
    }
    try:
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="running",
            payload=payload,
        )
        project = projects_store.get_project(project_id)
        if not isinstance(project, dict):
            raise LookupError("Project not found")

        result = await generate_report(project_id, projects_store)
        report_id = str(result["report_id"])
        content = str(result["content"])
        created_at = str(result["created_at"])
        metadata = result.get("metadata", {})

        projects_store.save_report(
            project_id,
            report_id=report_id,
            format="markdown",
            content=content,
            metadata=metadata,
        )

        target = str(metadata.get("target", "")).strip() or project_id
        html_content = _markdown_to_html(content, target=target, generated_at=created_at)
        projects_store.save_report(
            project_id,
            report_id=str(uuid.uuid4()),
            format="html",
            content=html_content,
            metadata=metadata,
        )

        logger.info(
            "report_generated",
            project_id=project_id,
            run_id=run_id,
            report_id=report_id,
            content_length=len(content),
        )
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="completed",
            payload={
                **payload,
                "report_id": report_id,
                "format": "markdown",
                "created_at": created_at,
                "metadata": metadata,
            },
        )
    except asyncio.CancelledError:
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="cancelled",
            payload={
                **payload,
                "error": "Report generation was cancelled.",
            },
        )
        raise
    except Exception as exc:
        logger.exception(
            "report_generation_failed",
            project_id=project_id,
            run_id=run_id,
            error=str(exc),
        )
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="failed",
            payload={
                **payload,
                "error": str(exc).strip() or type(exc).__name__,
            },
        )
    finally:
        _report_tasks.pop(run_id, None)


@router.post("/api/projects/{project_id}/reports/generate")
async def generate_project_report(project_id: str) -> GenerateReportResponse:
    """Start pentest report generation as a durable background run."""
    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    active_run = projects_store.get_latest_task_run(
        project_id,
        task_type="report",
        statuses={"pending", "running"},
    )
    if isinstance(active_run, dict):
        payload = active_run.get("payload", {})
        if not isinstance(payload, dict):
            payload = {}
        return GenerateReportResponse(
            ok=True,
            run_id=str(active_run.get("run_id", "")),
            status=str(active_run.get("status", "running")),
            report_id=str(payload.get("report_id", "")),
            format=str(payload.get("format", "markdown")),
            created_at=str(active_run.get("created_at", "")),
        )

    run_id = str(uuid.uuid4())
    _persist_report_run(
        project_id=project_id,
        run_id=run_id,
        status="pending",
        payload={
            "project_id": project_id,
            "report_id": "",
            "format": "markdown",
            "error": "",
        },
    )
    _report_tasks[run_id] = asyncio.create_task(
        _generate_project_report_task(project_id, run_id),
        name=f"report_run_{run_id}",
    )

    return GenerateReportResponse(
        ok=True,
        run_id=run_id,
        status="pending",
        report_id="",
        format="markdown",
        created_at="",
    )


@router.get("/api/projects/{project_id}/reports/status")
async def get_report_status(project_id: str, response: Response) -> ReportStatusResponse:
    """Check which report formats exist for a project."""
    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    response.headers["Cache-Control"] = "no-store"
    response.headers["Pragma"] = "no-cache"
    status = projects_store.list_report_status(project_id)
    latest_run = projects_store.get_latest_task_run(
        project_id,
        task_type="report",
    )
    return ReportStatusResponse(
        markdown=bool(status.get("markdown")),
        html=bool(status.get("html")),
        pdf=bool(status.get("pdf")),
        generated_at=status.get("generated_at"),
        run_id=str(latest_run.get("run_id", "")) if isinstance(latest_run, dict) else None,
        run_status=str(latest_run.get("status", "")) if isinstance(latest_run, dict) else None,
    )


@router.get("/api/projects/{project_id}/reports/{report_format}")
async def get_report_content(project_id: str, report_format: str, response: Response) -> ReportContentResponse:
    """Get a report's content by format."""
    if report_format not in {"markdown", "html", "pdf"}:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {report_format}")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    report = projects_store.get_report(project_id, format=report_format)
    if report is None:
        raise HTTPException(status_code=404, detail=f"No {report_format} report found for this project")

    response.headers["Cache-Control"] = "no-store"
    response.headers["Pragma"] = "no-cache"
    return ReportContentResponse(
        ok=True,
        format=str(report["format"]),
        content=str(report["content"]),
        metadata=report.get("metadata", {}),
        created_at=str(report["created_at"]),
    )


@router.post("/api/projects/{project_id}/reports/export")
async def export_report_download(project_id: str, request: ExportReportRequest) -> Response:
    """Export a password-protected report download."""
    safe_format = str(request.format or "markdown").strip().lower()
    password = str(request.password or "")
    if safe_format not in {"markdown", "html", "pdf"}:
        raise HTTPException(status_code=400, detail=f"Unsupported export format: {safe_format}")
    if not password.strip():
        raise HTTPException(status_code=400, detail="Export password is required.")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    html_report = projects_store.get_report(project_id, format="html")
    markdown_report = projects_store.get_report(project_id, format="markdown")
    source_report = html_report if safe_format == "html" else markdown_report
    if safe_format == "pdf":
        source_report = markdown_report or html_report
    if source_report is None:
        raise HTTPException(status_code=404, detail=f"No source report found for {safe_format} export")

    base_name = f"pentaforge-report-{project_id[:8]}"
    if safe_format == "markdown":
        inner_name = f"{base_name}.md"
        payload = str(source_report["content"]).encode("utf-8")
    elif safe_format == "html":
        inner_name = f"{base_name}.html"
        payload = str(source_report["content"]).encode("utf-8")
    else:
        pdf_bytes = _build_pdf_export_bytes(
            project_id=project_id,
            content=str(source_report["content"]),
            source_format=str(source_report["format"]),
        )
        payload = _encrypt_pdf_bytes(pdf_bytes, password)
        file_name = f"{base_name}.pdf"
        headers = {
            "Content-Disposition": f'attachment; filename="{file_name}"',
            "Cache-Control": "no-store",
            "Pragma": "no-cache",
            "X-Archive-Format": safe_format,
        }
        return Response(content=payload, media_type="application/pdf", headers=headers)

    archive_bytes = _build_protected_zip_bytes(
        inner_name=inner_name,
        payload=payload,
        password=password.strip(),
        encryption_method="ZipCrypto",
    )
    archive_name = f"{inner_name}.zip"
    headers = {
        "Content-Disposition": f'attachment; filename="{archive_name}"',
        "Cache-Control": "no-store",
        "Pragma": "no-cache",
        "X-Archive-Format": safe_format,
    }
    return Response(content=archive_bytes, media_type="application/zip", headers=headers)


@router.delete("/api/projects/{project_id}/reports/{report_format}")
async def delete_report(project_id: str, report_format: str) -> dict:
    """Delete a specific report format."""
    if report_format not in {"markdown", "html", "pdf"}:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {report_format}")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    deleted = projects_store.delete_report(project_id, format=report_format)
    return {"ok": True, "deleted": deleted, "format": report_format}


@router.put("/api/projects/{project_id}/reports/{report_format}")
async def update_report(project_id: str, report_format: str, request: UpdateReportRequest) -> ReportContentResponse:
    """Update a specific report format (markdown) and regenerate HTML."""
    if report_format != "markdown":
        raise HTTPException(status_code=400, detail="Only markdown reports can be manually edited.")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    existing_report = projects_store.get_report(project_id, format="markdown")
    if existing_report is None:
        raise HTTPException(status_code=404, detail="No markdown report found to edit.")

    metadata = existing_report.get("metadata", {})
    report_id = str(existing_report.get("id", uuid.uuid4()))
    created_at = str(existing_report.get("created_at", ""))

    new_content = request.content.strip()

    # Save Markdown
    projects_store.save_report(
        project_id,
        report_id=report_id,
        format="markdown",
        content=new_content,
        metadata=metadata,
    )

    # Regenerate HTML
    target = str(metadata.get("target", "")) or project_id
    html_content = _markdown_to_html(new_content, target=target, generated_at=created_at)
    
    existing_html = projects_store.get_report(project_id, format="html")
    html_report_id = str(existing_html.get("id", uuid.uuid4())) if existing_html else str(uuid.uuid4())
    
    projects_store.save_report(
        project_id,
        report_id=html_report_id,
        format="html",
        content=html_content,
        metadata=metadata,
    )

    return ReportContentResponse(
        ok=True,
        format="markdown",
        content=new_content,
        metadata=metadata,
        created_at=created_at,
    )
