"""Report generation and retrieval routes."""

from __future__ import annotations

import uuid

import markdown as md
import structlog
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from server.agents.report.report_generator import generate_report
from server.api.dependencies import projects_store

router = APIRouter(tags=["reports"])
logger = structlog.get_logger(__name__)


class GenerateReportResponse(BaseModel):
    ok: bool = True
    report_id: str = ""
    format: str = "markdown"
    created_at: str = ""


class ReportStatusResponse(BaseModel):
    markdown: bool = False
    html: bool = False
    pdf: bool = False
    generated_at: str | None = None


class ReportContentResponse(BaseModel):
    ok: bool = True
    format: str = "markdown"
    content: str = ""
    metadata: dict = {}
    created_at: str = ""


_HTML_REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PentaForge Pentest Report — {target}</title>
<style>
  :root {{
    --bg: #0c1220;
    --surface: #111827;
    --border: #1e293b;
    --text: #e2e8f0;
    --text-muted: #94a3b8;
    --accent: #6366f1;
    --critical: #ef4444;
    --high: #f97316;
    --medium: #eab308;
    --low: #3b82f6;
    --info: #6b7280;
  }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.7;
    padding: 2rem;
    max-width: 960px;
    margin: 0 auto;
  }}
  h1 {{ font-size:1.8rem; margin:1.5rem 0 1rem; color:#f1f5f9; border-bottom:2px solid var(--accent); padding-bottom:.5rem; }}
  h2 {{ font-size:1.4rem; margin:1.5rem 0 .8rem; color:#e2e8f0; }}
  h3 {{ font-size:1.1rem; margin:1.2rem 0 .5rem; color:#cbd5e1; }}
  p {{ margin:.5rem 0; }}
  ul, ol {{ margin:.5rem 0 .5rem 1.5rem; }}
  li {{ margin:.25rem 0; }}
  code {{
    background: var(--surface);
    padding: .15em .4em;
    border-radius: 4px;
    font-size: .9em;
    border: 1px solid var(--border);
  }}
  pre {{
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    border: 1px solid var(--border);
    overflow-x: auto;
    margin: .5rem 0;
    font-size: .85em;
  }}
  pre code {{ background:none; border:none; padding:0; }}
  table {{
    width:100%;
    border-collapse:collapse;
    margin:.5rem 0;
  }}
  th, td {{
    padding:.5rem .75rem;
    border:1px solid var(--border);
    text-align:left;
  }}
  th {{ background:var(--surface); font-weight:600; }}
  strong {{ color:#f1f5f9; }}
  a {{ color: var(--accent); text-decoration:none; }}
  a:hover {{ text-decoration:underline; }}
  hr {{ border:none; border-top:1px solid var(--border); margin:1.5rem 0; }}
  .header {{
    text-align:center;
    padding:2rem 0;
    border-bottom:2px solid var(--accent);
    margin-bottom:2rem;
  }}
  .header h1 {{ border:none; font-size:2rem; }}
  .header p {{ color:var(--text-muted); font-size:.9rem; }}
  .footer {{
    text-align:center;
    padding:2rem 0;
    border-top:1px solid var(--border);
    margin-top:2rem;
    color:var(--text-muted);
    font-size:.8rem;
  }}
  @media print {{
    body {{ background:#fff; color:#1a1a1a; }}
    h1, h2, h3, strong {{ color:#0f172a; }}
    code {{ background:#f1f5f9; border-color:#e2e8f0; }}
    pre {{ background:#f8fafc; border-color:#e2e8f0; }}
    .header {{ border-color:#6366f1; }}
  }}
</style>
</head>
<body>
<div class="header">
  <h1>PentaForge Penetration Test Report</h1>
  <p>Target: {target} &mdash; Generated: {generated_at}</p>
</div>
{body}
<div class="footer">
  <p>Generated by PentaForge &mdash; Automated Penetration Testing Platform</p>
</div>
</body>
</html>
"""


def _markdown_to_html(markdown_content: str, target: str, generated_at: str) -> str:
    """Convert markdown report to styled HTML."""
    body = md.markdown(
        markdown_content,
        extensions=["tables", "fenced_code", "toc"],
    )
    return _HTML_REPORT_TEMPLATE.format(
        target=target,
        generated_at=generated_at,
        body=body,
    )


@router.post("/api/projects/{project_id}/reports/generate")
async def generate_project_report(project_id: str) -> GenerateReportResponse:
    """Generate a pentest report for a project using LLM."""
    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    try:
        result = await generate_report(project_id, projects_store)
    except Exception as exc:
        logger.exception(
            "report_generation_failed",
            project_id=project_id,
            error=str(exc),
        )
        raise HTTPException(
            status_code=500,
            detail=f"Report generation failed: {str(exc).strip() or type(exc).__name__}",
        )

    report_id = str(result["report_id"])
    content = str(result["content"])
    created_at = str(result["created_at"])
    metadata = result.get("metadata", {})

    # Save markdown.
    projects_store.save_report(
        project_id,
        report_id=report_id,
        format="markdown",
        content=content,
        metadata=metadata,
    )

    # Generate and save HTML.
    target = str(metadata.get("target", "")).strip() or project_id
    html_content = _markdown_to_html(content, target=target, generated_at=created_at)
    projects_store.save_report(
        project_id,
        report_id=str(uuid.uuid4()),
        format="html",
        content=html_content,
        metadata=metadata,
    )

    logger.info(
        "report_generated",
        project_id=project_id,
        report_id=report_id,
        content_length=len(content),
    )

    return GenerateReportResponse(
        ok=True,
        report_id=report_id,
        format="markdown",
        created_at=created_at,
    )


@router.get("/api/projects/{project_id}/reports/status")
async def get_report_status(project_id: str) -> ReportStatusResponse:
    """Check which report formats exist for a project."""
    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    status = projects_store.list_report_status(project_id)
    return ReportStatusResponse(
        markdown=bool(status.get("markdown")),
        html=bool(status.get("html")),
        pdf=bool(status.get("pdf")),
        generated_at=status.get("generated_at"),
    )


@router.get("/api/projects/{project_id}/reports/{report_format}")
async def get_report_content(project_id: str, report_format: str) -> ReportContentResponse:
    """Get a report's content by format."""
    if report_format not in {"markdown", "html", "pdf"}:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {report_format}")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    report = projects_store.get_report(project_id, format=report_format)
    if report is None:
        raise HTTPException(status_code=404, detail=f"No {report_format} report found for this project")

    return ReportContentResponse(
        ok=True,
        format=str(report["format"]),
        content=str(report["content"]),
        metadata=report.get("metadata", {}),
        created_at=str(report["created_at"]),
    )


@router.delete("/api/projects/{project_id}/reports/{report_format}")
async def delete_report(project_id: str, report_format: str) -> dict:
    """Delete a specific report format."""
    if report_format not in {"markdown", "html", "pdf"}:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {report_format}")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    deleted = projects_store.delete_report(project_id, format=report_format)
    return {"ok": True, "deleted": deleted, "format": report_format}
