"""Report generation and retrieval routes."""

from __future__ import annotations

import asyncio
import uuid

import markdown as md
import structlog
from fastapi import APIRouter, HTTPException, Response
from pydantic import BaseModel, Field

from server.agents.report.report_generator import generate_report
from server.api.dependencies import projects_store

router = APIRouter(tags=["reports"])
logger = structlog.get_logger(__name__)
_report_tasks: dict[str, asyncio.Task[None]] = {}


class GenerateReportResponse(BaseModel):
    ok: bool = True
    run_id: str = ""
    status: str = "pending"
    report_id: str = ""
    format: str = "markdown"
    created_at: str = ""


class ReportStatusResponse(BaseModel):
    markdown: bool = False
    html: bool = False
    pdf: bool = False
    generated_at: str | None = None
    run_id: str | None = None
    run_status: str | None = None


class ReportContentResponse(BaseModel):
    ok: bool = True
    format: str = "markdown"
    content: str = ""
    metadata: dict = {}
    created_at: str = ""


_HTML_REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PentaForge Pentest Report — {target}</title>
<style>
  :root {{
    --bg: #ffffff;
    --surface: #f8fafc;
    --border: #e2e8f0;
    --text: #1e293b;
    --text-muted: #64748b;
    --accent: #4f46e5;
    --critical: #ef4444;
    --high: #f97316;
    --medium: #eab308;
    --low: #3b82f6;
    --info: #6b7280;
    --heading: #0f172a;
  }}
  [data-theme="dark"] {{
    --bg: #0c1220;
    --surface: #111827;
    --border: #1e293b;
    --text: #e2e8f0;
    --text-muted: #94a3b8;
    --accent: #6366f1;
    --heading: #f1f5f9;
  }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    color-scheme: light dark;
    line-height: 1.7;
    padding: 2rem;
    max-width: 960px;
    margin: 0 auto;
  }}
  h1 {{ font-size:1.8rem; margin:1.5rem 0 1rem; color:var(--heading); border-bottom:2px solid var(--accent); padding-bottom:.5rem; }}
  h2 {{ font-size:1.4rem; margin:1.5rem 0 .8rem; color:var(--heading); }}
  h3 {{ font-size:1.1rem; margin:1.2rem 0 .5rem; color:var(--heading); }}
  p {{ margin:.5rem 0; }}
  ul, ol {{ margin:.5rem 0 .5rem 1.5rem; }}
  li {{ margin:.25rem 0; }}
  code {{
    background: var(--surface);
    padding: .15em .4em;
    border-radius: 4px;
    font-size: .9em;
    border: 1px solid var(--border);
  }}
  pre {{
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    border: 1px solid var(--border);
    overflow-x: auto;
    margin: .5rem 0;
    font-size: .85em;
  }}
  pre code {{ background:none; border:none; padding:0; }}
  table {{
    width:100%;
    border-collapse:collapse;
    margin:.5rem 0;
  }}
  th, td {{
    padding:.5rem .75rem;
    border:1px solid var(--border);
    text-align:left;
  }}
  th {{ background:var(--surface); font-weight:600; color:var(--heading); }}
  strong {{ color:var(--heading); }}
  a {{ color: var(--accent); text-decoration:none; }}
  a:hover {{ text-decoration:underline; }}
  hr {{ border:none; border-top:1px solid var(--border); margin:1.5rem 0; }}
  .header {{
    text-align:center;
    padding:2rem 0;
    border-bottom:2px solid var(--accent);
    margin-bottom:2rem;
  }}
  .header h1 {{ border:none; font-size:2rem; }}
  .header p {{ color:var(--text-muted); font-size:.9rem; }}
  .footer {{
    text-align:center;
    padding:2rem 0;
    border-top:1px solid var(--border);
    margin-top:2rem;
    color:var(--text-muted);
    font-size:.8rem;
  }}
  @media print {{
    body {{ background:#fff; color:#1a1a1a; }}
    h1, h2, h3, strong {{ color:#0f172a; }}
    code {{ background:#f1f5f9; border-color:#e2e8f0; }}
    pre {{ background:#f8fafc; border-color:#e2e8f0; }}
    .header {{ border-color:#6366f1; }}
  }}
</style>
</head>
<body>
<div class="header">
  <h1>PentaForge Penetration Test Report</h1>
  <p>Target: {target} &mdash; Generated: {generated_at}</p>
</div>
{body}
<div class="footer">
  <p>Generated by PentaForge &mdash; Automated Penetration Testing Platform</p>
</div>
</body>
</html>
"""


def _markdown_to_html(markdown_content: str, target: str, generated_at: str) -> str:
    """Convert markdown report to styled HTML."""
    content = markdown_content.strip()
    # Remove LLM wrapping if present
    if content.startswith("```markdown"):
        content = content[len("```markdown") :].strip()
        if content.endswith("```"):
            content = content[:-3].strip()
    elif content.startswith("```"):
        content = content[3:].strip()
        if content.endswith("```"):
            content = content[:-3].strip()

    body = md.markdown(
        content,
        extensions=["tables", "fenced_code", "toc"],
    )
    return _HTML_REPORT_TEMPLATE.format(
        target=target,
        generated_at=generated_at,
        body=body,
    )


def _persist_report_run(
    *,
    project_id: str,
    run_id: str,
    status: str,
    payload: dict,
) -> None:
    projects_store.upsert_task_run(
        run_id=run_id,
        project_id=project_id,
        task_type="report",
        status=status,
        payload=payload,
    )


async def _generate_project_report_task(project_id: str, run_id: str) -> None:
    payload: dict = {
        "project_id": project_id,
        "report_id": "",
        "format": "markdown",
        "error": "",
    }
    try:
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="running",
            payload=payload,
        )
        project = projects_store.get_project(project_id)
        if not isinstance(project, dict):
            raise LookupError("Project not found")

        result = await generate_report(project_id, projects_store)
        report_id = str(result["report_id"])
        content = str(result["content"])
        created_at = str(result["created_at"])
        metadata = result.get("metadata", {})

        projects_store.save_report(
            project_id,
            report_id=report_id,
            format="markdown",
            content=content,
            metadata=metadata,
        )

        target = str(metadata.get("target", "")).strip() or project_id
        html_content = _markdown_to_html(content, target=target, generated_at=created_at)
        projects_store.save_report(
            project_id,
            report_id=str(uuid.uuid4()),
            format="html",
            content=html_content,
            metadata=metadata,
        )

        logger.info(
            "report_generated",
            project_id=project_id,
            run_id=run_id,
            report_id=report_id,
            content_length=len(content),
        )
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="completed",
            payload={
                **payload,
                "report_id": report_id,
                "format": "markdown",
                "created_at": created_at,
                "metadata": metadata,
            },
        )
    except asyncio.CancelledError:
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="cancelled",
            payload={
                **payload,
                "error": "Report generation was cancelled.",
            },
        )
        raise
    except Exception as exc:
        logger.exception(
            "report_generation_failed",
            project_id=project_id,
            run_id=run_id,
            error=str(exc),
        )
        _persist_report_run(
            project_id=project_id,
            run_id=run_id,
            status="failed",
            payload={
                **payload,
                "error": str(exc).strip() or type(exc).__name__,
            },
        )
    finally:
        _report_tasks.pop(run_id, None)


@router.post("/api/projects/{project_id}/reports/generate")
async def generate_project_report(project_id: str) -> GenerateReportResponse:
    """Start pentest report generation as a durable background run."""
    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    active_run = projects_store.get_latest_task_run(
        project_id,
        task_type="report",
        statuses={"pending", "running"},
    )
    if isinstance(active_run, dict):
        payload = active_run.get("payload", {})
        if not isinstance(payload, dict):
            payload = {}
        return GenerateReportResponse(
            ok=True,
            run_id=str(active_run.get("run_id", "")),
            status=str(active_run.get("status", "running")),
            report_id=str(payload.get("report_id", "")),
            format=str(payload.get("format", "markdown")),
            created_at=str(active_run.get("created_at", "")),
        )

    run_id = str(uuid.uuid4())
    _persist_report_run(
        project_id=project_id,
        run_id=run_id,
        status="pending",
        payload={
            "project_id": project_id,
            "report_id": "",
            "format": "markdown",
            "error": "",
        },
    )
    _report_tasks[run_id] = asyncio.create_task(
        _generate_project_report_task(project_id, run_id),
        name=f"report_run_{run_id}",
    )

    return GenerateReportResponse(
        ok=True,
        run_id=run_id,
        status="pending",
        report_id="",
        format="markdown",
        created_at="",
    )


@router.get("/api/projects/{project_id}/reports/status")
async def get_report_status(project_id: str, response: Response) -> ReportStatusResponse:
    """Check which report formats exist for a project."""
    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    response.headers["Cache-Control"] = "no-store"
    response.headers["Pragma"] = "no-cache"
    status = projects_store.list_report_status(project_id)
    latest_run = projects_store.get_latest_task_run(
        project_id,
        task_type="report",
    )
    return ReportStatusResponse(
        markdown=bool(status.get("markdown")),
        html=bool(status.get("html")),
        pdf=bool(status.get("pdf")),
        generated_at=status.get("generated_at"),
        run_id=str(latest_run.get("run_id", "")) if isinstance(latest_run, dict) else None,
        run_status=str(latest_run.get("status", "")) if isinstance(latest_run, dict) else None,
    )


@router.get("/api/projects/{project_id}/reports/{report_format}")
async def get_report_content(project_id: str, report_format: str, response: Response) -> ReportContentResponse:
    """Get a report's content by format."""
    if report_format not in {"markdown", "html", "pdf"}:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {report_format}")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    report = projects_store.get_report(project_id, format=report_format)
    if report is None:
        raise HTTPException(status_code=404, detail=f"No {report_format} report found for this project")

    response.headers["Cache-Control"] = "no-store"
    response.headers["Pragma"] = "no-cache"
    return ReportContentResponse(
        ok=True,
        format=str(report["format"]),
        content=str(report["content"]),
        metadata=report.get("metadata", {}),
        created_at=str(report["created_at"]),
    )


@router.delete("/api/projects/{project_id}/reports/{report_format}")
async def delete_report(project_id: str, report_format: str) -> dict:
    """Delete a specific report format."""
    if report_format not in {"markdown", "html", "pdf"}:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {report_format}")

    project = projects_store.get_project(project_id)
    if not isinstance(project, dict):
        raise HTTPException(status_code=404, detail="Project not found")

    deleted = projects_store.delete_report(project_id, format=report_format)
    return {"ok": True, "deleted": deleted, "format": report_format}
