"""Configuration for the Analyzer agent."""

from __future__ import annotations

ANALYZER_MAX_TOOL_ROUNDS = 3
ANALYZER_LLM_CALL_TIMEOUT_SECONDS = 300
ANALYZER_MAX_TOOL_CALLS_PER_ROUND = 4

ANALYZER_VALID_VERDICTS = [
    "real_vulnerability",
    "false_positive",
    "inconclusive",
]
ANALYZER_DEFAULT_VERDICT = "inconclusive"

ANALYZER_MAX_INPUT_CHARS = 16000
ANALYZER_MAX_SUMMARY_CHARS = 480
ANALYZER_MAX_NORMALIZED_EVIDENCE_ITEMS = 10
ANALYZER_HITL_DECISIONS = ("ACT",)

ACT_MIN_CVSS = 9.0
ATTEND_MIN_CVSS = 7.0
ACT_MIN_EPSS = 0.20
ATTEND_MIN_EPSS = 0.05
ACT_MIN_SCORE = 0.78
ATTEND_MIN_SCORE = 0.42

SCREENSHOT_TIMEOUT = 30000
SCREENSHOT_VIEWPORT_WIDTH = 1920
SCREENSHOT_VIEWPORT_HEIGHT = 1080
SCREENSHOT_QUALITY = 90
SCREENSHOT_FORMAT = "png"
SCREENSHOT_STORAGE_PATH = "/tmp/pentaforge/screenshots"
REDACT_URL_PARAMS = True
REDACT_FORM_DATA = True
REDACT_COOKIES = True
BROWSER_TYPE = "chromium"
BROWSER_HEADLESS = True
BROWSER_IGNORE_HTTPS_ERRORS = True
BROWSER_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 PentaForge/1.0"
)
ANNOTATION_COLOR = "#FF0000"
ANNOTATION_BORDER_WIDTH = 3
EVIDENCE_HASH_ALGORITHM = "sha256"

VISION_MODEL = "llava:13b"
VISION_TIMEOUT = 60
VISION_MAX_TOKENS = 2000
VISION_CONFIDENCE_THRESHOLD = 0.7
FALSE_POSITIVE_THRESHOLD = 0.8
